name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.16.0"
          rebar3-version: "3"
      - uses: oven-sh/setup-bun@v2
      - run: gleam deps download
      - run: gleam run -m lustre/dev build time_zone_fren --minify
      - name: Add CNAME
        run: echo "time.bucsi.net" > dist/CNAME
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - id: deployment
        uses: actions/deploy-pages@v4
